# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# GitHub Actions Workflow created for handling the release process based on the draft release prepared with the Build workflow.

name: Publish
on:
  release:
    types: [prereleased, released]

jobs:
  # Publish the packages to NuGet
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      # Download the artifacts from the release and publish them to NuGet
      - name: Download Artifacts
        run: gh release download "${{ github.event.release.tag_name }}" --pattern '*nupkg'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to NuGet
        run: dotnet nuget push "*.nupkg" --source "nuget.org" --api-key "$NUGET_APIKEY"
        env:
          NUGET_APIKEY: ${{ secrets.NUGET_APIKEY }}